on:
  push:
    branches:
      - main
name: Deploy website on push to main
jobs:
  production-web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: test echo
      run:  echo "PROD"
    - name: Update config files
      run:  ./infrastructure/update-config-PROD.sh
